---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          # known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa
          if_key_exists: replace
          known_hosts: unnecessary
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      #https://github.com/benwinding/dokku-pages
      - name: Push
        run: |
          npm i -g dokku-pages
          git config --global user.email "hi@typora.io"
          git config --global user.name "Typora"
          dokku-pages deploy -g dokku@106.15.186.16:wiki --minimal -d dist
          rm -rf dist
      
